app:
    resource: '@AppBundle/Controller/'
    type: annotation
ideas:
    path: /ideas
    defaults: {_controller: AppBundle:Idea:index}
homepage:
    path: /
    defaults: {_controller: AppBundle:Default:index}