app:
    resource: '@AppBundle/Controller/'
    type: annotation
ideas:
    path: /ideas
    defaults: {_controller: AppBundle:Idea:index}
idea:
    path: /idea/{id}
    defaults: {_controller: AppBundle:Idea:idea}
    requirements:
        id: \d+
homepage:
    path: /
    defaults: {_controller: AppBundle:Default:index}
